export const generatePermanentId = (prefix: string, num: number) => {
  return `${prefix}${(1000 + num).toString().slice(-4)}`;
};

export const generateSkuId = (title: string) => {
  const code = title.replace(/\s+/g, '-').toUpperCase().slice(0, 6);
  return `${code}-${Date.now().toString().slice(-5)}`;
};

export const generateSixDigitAlphaNumericCode = () => {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = '';
  for (let i = 0; i < 6; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
};

export const autoGeneratedPassword = () => {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789#$&@%';
  let result = '';
  for (let i = 0; i < 8; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
};